### ISSUE TITLE
Hi, Is this code for ECCV2020(Oral) article 'Prototype Rectification for Few-Shot Learning'? Are you the author of the paper?

### ISSUE THREAD

**Issue by tianyaxjsw** [skingorz/UPR-FSL#1]
Hi, Thank you for sharing. Is this code for ECCV2020(Oral) article 'Prototype Rectification for Few-Shot Learning'? Are you the author of the paper?

**Comment by skingorz** [comment]
No

**Comment by skingorz** [comment]
> Hi, Thank you for sharing. Is this code for ECCV2020(Oral) article 'Prototype Rectification for Few-Shot Learning'? Are you the author of the paper?

This code is for  another unpublished paper and I'm not the author for 'Prototype Rectification for Few-Shot Learning'.
